swagger: "2.0"
info:
  title: My API
  description: "This is my API"
  version: "1.0.0"
host: //
schemes:
- https
paths:
  /tasks:
    get:
      summary: "Get a list of tasks"
      operationId: getTasks
      responses:
        200:
          description: "OK"

securityDefinitions:
  api_key:
    type: "apiKey"
    name: "key"
    in: "query"
security:
  - api_key: []